### ISSUE TITLE
some error occurs when openman convert

### ISSUE THREAD

**Issue by fei12990** [codeasashu/openman#1]
Traceback (most recent call last):
  File "/usr/local/bin/openman", line 11, in <module>
    load_entry_point('Openman==0.1.0', 'console_scripts', 'openman')()
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/Openman-0.1.0-py3.8.egg/openman/cli.py", line 23, in convert
    ignore_file = os.path.join(ignore) or None
  File "/usr/local/lib/python3.8/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by codeasashu** [comment]
@fei12990 Can you tell me how did you tried to use this? What was the input given, which led to this output?

**Comment by fei12990** [comment]
command: `openman convert -f json Postman_Echo.postman_collection.json spec.yaml`,
Postman_Echo.postman_collection.json is exported from postman.[

**Comment by fei12990** [comment]
[Postman Echo.postman_collection.txt](https://github.com/codeasashu/openman/files/4000605/Postman.Echo.postman_collection.txt)
github cannot attach json file. I renamed it TXT

**Comment by codeasashu** [comment]
Hello @fei12990 , Thank you for taking time and using this library. One more thing I forgot to mention: This library only works with postman export in Collection ver 2.1.0, while the one you provided is v2.0.0.

Can you please try exporting your postman collection in v2.1.0 format and then try this out?
