### ISSUE TITLE
openapi_spec_validator.handlers

### ISSUE THREAD

**Issue by mstdoc** [codeasashu/openman#15]
Hi.
After installing openman with "pip install openman"
and trying to perform any command, e.g. "openman --help"
i'm getting error like:

ModuleNotFoundError: No module named 'openapi_spec_validator.handlers'

Tried python 3.7.15 and 3.8.15
What am i doing wrong?

**Comment by davidwincent** [comment]
Same issue here.

Output from `openman --help` :
```
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39/bin/openman", line 5, in <module>
    from openman.cli import cli
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39/lib/python3.9/site-packages/openman/cli.py", line 7, in <module>
    from .mock import Mock
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39/lib/python3.9/site-packages/openman/mock/__init__.py", line 1, in <module>
    from .mock import Mock
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39/lib/python3.9/site-packages/openman/mock/mock.py", line 1, in <module>
    import connexion
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39/lib/python3.9/site-packages/connexion/__init__.py", line 5, in <module>
    from .apis import AbstractAPI  # NOQA
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39/lib/python3.9/site-packages/connexion/apis/__init__.py", line 1, in <module>
    from .abstract import AbstractAPI  # NOQA
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39/lib/python3.9/site-packages/connexion/apis/abstract.py", line 10, in <module>
    from ..operations import make_operation
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39/lib/python3.9/site-packages/connexion/operations/__init__.py", line 1, in <module>
    from .abstract import AbstractOperation  # noqa
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39/lib/python3.9/site-packages/connexion/operations/abstract.py", line 10, in <module>
    from ..decorators.response import ResponseValidator
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39/lib/python3.9/site-packages/connexion/decorators/response.py", line 12, in <module>
    from .validation import ResponseBodyValidator
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39/lib/python3.9/site-packages/connexion/decorators/validation.py", line 15, in <module>
    from ..json_schema import Draft4RequestValidator, Draft4ResponseValidator
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39/lib/python3.9/site-packages/connexion/json_schema.py", line 7, in <module>
    from openapi_spec_validator.handlers import UrlHandler
ModuleNotFoundError: No module named 'openapi_spec_validator.handlers'
```

|  Component  |  Version |
|---|---|
|  Openman  |  1.1.1 |
|  Python  |  3.9.7 |
|  OS  |  macOS Ventura 13.0 |
|  Platform  |  Apple M1 Pro |

**Comment by codeasashu** [comment]
@davidwincent @mstdoc thank you for reporting.
