### ISSUE TITLE
openman.errors.RequestItemParserException: Not a valid request

### ISSUE THREAD

**Issue by shuarey** [codeasashu/openman#6]
Attempted to execute the following command:

`C:\Users\{User}\AppData\Local\Programs\Python\Python39\Scripts>openman convert -f json collection.json swagger.json`

no output file this time. Just the following error:

`Traceback (most recent call last):
  File "c:\users\{user}\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\{user}\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\{user}\AppData\Local\Programs\Python\Python39\Scripts\openman.exe\__main__.py", line 7, in <module>
  File "c:\users\{user}\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\{user}\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\{user}\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\{user}\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\{user}\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\{user}\appdata\local\programs\python\python39\lib\site-packages\openman\cli.py", line 36, in convert
    apispec = spec.get_spec(ignorespec=ignore_file)
  File "c:\users\{user}\appdata\local\programs\python\python39\lib\site-packages\openman\spec\spec.py", line 52, in get_spec
    for requestitem in self.postman_collection.get_requestitems():
  File "c:\users\{user}\appdata\local\programs\python\python39\lib\site-packages\openman\parser\collection.py", line 54, in get_requestitems
    items.extend(folder.get_requestitems())
  File "c:\users\{user}\appdata\local\programs\python\python39\lib\site-packages\openman\parser\folder.py", line 40, in get_requestitems
    request_items.append(RequestItem(item))
  File "c:\users\{user}\appdata\local\programs\python\python39\lib\site-packages\openman\parser\requestitem.py", line 11, in __init__
    raise RequestItemParserException('Not a valid request')
openman.errors.RequestItemParserException: Not a valid request`

**Comment by codeasashu** [comment]
@shuarey Can you kindly re-share the collection you're trying to convert? Its most likely some schema issues

**Comment by shuarey** [comment]
[collection.txt](https://github.com/codeasashu/openman/files/6648340/collection.txt)

**Comment by codeasashu** [comment]
@shuarey please check now. If still an issue, kindly reopen. Thanks for pointing this out

**Comment by shuarey** [comment]
@codeasashu Thank you very much for resolving this for me! This was exactly what I was looking for.
