### ISSUE TITLE
Float handling error

### ISSUE THREAD

**Issue by faveoled** [codeasashu/openman#7]
I tried to convert my Postman 2.1 collection to OpenAPI and got a failure.
```
Traceback (most recent call last):
  File "/home/user/.local/bin/openman", line 8, in <module>
    sys.exit(cli())
  File "/home/user/.local/lib/python3.9/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/lib/python3.9/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/lib/python3.9/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/lib/python3.9/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/lib/python3.9/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.local/lib/python3.9/site-packages/openman/cli.py", line 36, in convert
    apispec = spec.get_spec(ignorespec=ignore_file)
  File "/home/user/.local/lib/python3.9/site-packages/openman/spec/spec.py", line 55, in get_spec
    operations=Operation(requestitem, ignorespec=ignorespec).get(),
  File "/home/user/.local/lib/python3.9/site-packages/openman/spec/operation.py", line 54, in get
    _operation[method]['responses'] = self.responses() or\
  File "/home/user/.local/lib/python3.9/site-packages/openman/spec/operation.py", line 63, in responses
    schema = SchemaConvertor.convert(response.body, ignore=ignoreschema)
  File "/home/user/.local/lib/python3.9/site-packages/openman/schema_converter.py", line 99, in convert
    schema = cls()._walker(item)
  File "/home/user/.local/lib/python3.9/site-packages/openman/schema_converter.py", line 45, in _walker
    schema['properties'][k] = self._walker(v)
  File "/home/user/.local/lib/python3.9/site-packages/openman/schema_converter.py", line 29, in _walker
    (_type, _format) = python2schematypes[type(item)]
KeyError: <class 'float'>

```

**Comment by codeasashu** [comment]
@faveoled I hope this fixes it. If issue still occurs, please attach a sample postman collection to replicate

**Comment by faveoled** [comment]
@codeasashu Thanks, it fixed the problem.
